# Group roles

# Create role [/api/v1/roles]

## Create Role [POST]

Creates a role

+   Request Create User (application/json)

	+   Body

            {
                "role": "ADMIN",
                "level": 1
            }

+   Response 200 (application/json)

            {
                "id": "5b5c7987951e737d777909a2",
                "role": "ADMIN",
                "level": 1
            }
